spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://postgres:5432/statrack
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-version: 1
    baseline-on-migrate: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres:5432/statrack

  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    host: rabbitmq

  mail:
    host: smtp.gmail.com
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      debug: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework: DEBUG
    root: INFO

frontend:
  url: ${FRONTEND_URL}


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${ACCESS_TOKEN_EXPIRY}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRY}
  cors:
    origins: http://frontend:3000, http://backend:8080, http://localhost:3000, http://production-frontend.com


file:
  upload-dir: uploads/