spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/statrack
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:statrack}
    password: ${DB_PASSWORD:statrack}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-version: 1
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework: DEBUG
    root: INFO

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:your-default-secret-key}
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}

file:
  upload-dir: ${FILE_UPLOAD_DIR:uploads/}
