version: '3.8'

services:
  backend:
    image: hlyudzyk/statrack:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env.backend
  frontend:
    image: hlyudzyk/statrack-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
  postgres:
    image: postgres:16
    env_file:
      - .env.backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:latest'
    env_file:
      - .env.backend
    ports:
      - '5672:5672'

volumes:
  postgres_data:
