version: '3.8'

services:
  app:
    container_name: "backend"
    build:
      context: statrack/
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/statrack
      SPRING_DATASOURCE_USERNAME: statrack
      SPRING_DATASOURCE_PASSWORD: statrack

  frontend:
    container_name: "frontend"
    build:
      context: frontend/
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

  postgres:
    container_name: 'app-db'
    image: postgres:16
    environment:
      POSTGRES_DB: statrack
      POSTGRES_USER: statrack
      POSTGRES_PASSWORD: statrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: 'app-message-broker'
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=statrack'
      - 'RABBITMQ_DEFAULT_USER=statrack'
    ports:
      - '5672:5672'
volumes:
  postgres_data:
