version: '3.8'

services:
  backend:
    build:
      context: statrack/
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env.backend
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.frontend
  postgres:
    image: postgres:16
    env_file:
      - .env.backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:latest'
    env_file:
      - .env.backend
    ports:
      - '5672:5672'

volumes:
  postgres_data:
